# Fibonacci
# 
# Each new term in the Fibonaccie sequence is generated by adding the previous two terms.  By starting with 1 and 2, the first 10 terms will be:

#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By consider the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

if __name__ == "__main__":
    
    max_value = 4000000
    fib_values = [1, 2]
    fib_even = [2]
    count = 2
    fib = 0

    while( fib < max_value): 
        fib = fib_values[count-1] + fib_values[count-2]
        if (fib < max_value):
            fib_values.append(fib)
        if (fib % 2 == 0):
            fib_even.append(fib)
        count += 1
    print(fib_values)
    print(fib_even)
    print(sum(fib_even))    
