// Fibonacci
//
// Eac new term in the Fibanocci sequence is generated by adding the
// previous two terms.  By starting with 1 and 2, the first 10 terms
// will be:
//
// 1, 2, 3, , 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>

#define MAX_VALUE 4000000

int main(){
	// initialize values
	int fib_values[100] = {0};
	int fib_even[100] = {0};
	int fib_count = 2;
	int even_count = 1;
	int fib = 0;
	int fib_even_sum = 0;

	// setting the first two fibonacci values
	fib_values[0] = 1;
	fib_values[1] = 2;
	fib_even[0] = 2;

	// calculate the fibonacci sequence
	while( fib < MAX_VALUE ) {
		fib = fib_values[fib_count-1] + fib_values[fib_count-2];
		if( fib < MAX_VALUE)
			fib_values[fib_count] = fib;
		if( fib % 2 == 0) {
			fib_even[even_count] = fib;
			even_count++;
		}
		fib_count++;
	}	
	// sum the even values	
	for(int i=0; i < 100; i++)
		fib_even_sum += fib_even[i];

	printf("%d\n",fib_even_sum);

	return 0;
}
